//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grammophone.Domos.Domain.Workflow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grammophone.Domos.Domain.Workflow.StateResources", typeof(StateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the state, to be referred by the system..
        /// </summary>
        public static string CodeName_Description {
            get {
                return ResourceManager.GetString("CodeName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Name.
        /// </summary>
        public static string CodeName_Name {
            get {
                return ResourceManager.GetString("CodeName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional description of the state..
        /// </summary>
        public static string Description_Description {
            get {
                return ResourceManager.GetString("Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Name {
            get {
                return ResourceManager.GetString("Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True intended to be an end state..
        /// </summary>
        public static string IsEnd_Description {
            get {
                return ResourceManager.GetString("IsEnd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is End.
        /// </summary>
        public static string IsEnd_Name {
            get {
                return ResourceManager.GetString("IsEnd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True intended to be a start state..
        /// </summary>
        public static string IsStart_Description {
            get {
                return ResourceManager.GetString("IsStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Start.
        /// </summary>
        public static string IsStart_Name {
            get {
                return ResourceManager.GetString("IsStart_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name of the state..
        /// </summary>
        public static string Name_Description {
            get {
                return ResourceManager.GetString("Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        public static string Name_Name {
            get {
                return ResourceManager.GetString("Name_Name", resourceCulture);
            }
        }
    }
}
