//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grammophone.Domos.Domain.Accounting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FundsTransferBatchMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FundsTransferBatchMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grammophone.Domos.Domain.Accounting.FundsTransferBatchMessageResources", typeof(FundsTransferBatchMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional comments for the message..
        /// </summary>
        public static string Comments_Description {
            get {
                return ResourceManager.GetString("Comments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments_Name {
            get {
                return ResourceManager.GetString("Comments_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifier of the message..
        /// </summary>
        public static string GUID_Description {
            get {
                return ResourceManager.GetString("GUID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string GUID_Name {
            get {
                return ResourceManager.GetString("GUID_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional code for the message..
        /// </summary>
        public static string MessageCode_Description {
            get {
                return ResourceManager.GetString("MessageCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Code.
        /// </summary>
        public static string MessageCode_Name {
            get {
                return ResourceManager.GetString("MessageCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time of the message, in UTC..
        /// </summary>
        public static string Time_Description {
            get {
                return ResourceManager.GetString("Time_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time_Name {
            get {
                return ResourceManager.GetString("Time_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the messge..
        /// </summary>
        public static string Type_Description {
            get {
                return ResourceManager.GetString("Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type_Name {
            get {
                return ResourceManager.GetString("Type_Name", resourceCulture);
            }
        }
    }
}
